version: '3.8'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8000:80
      # Laravel port
      - 8001:81
    depends_on:
      - php
      - client

  # PHP FastCGI Process Manager container
  php:
    build:
      context: docker/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=0"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - postgres

  # PostgreSQL database container
  postgres:
    image: postgres:13
    volumes:
      # Database volume
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

# Client container
  client:
    build:
      context: docker/client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client

######### Volumes ###################################

volumes:
  database:
    driver: local