version: "3.8"

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root

    # Serviço para o Laravel (Backend)
    backend:
        build:
            context: ./laravel-backend
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - ./laravel-backend:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: base64:randomKeyHere
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: root
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - postgres

volumes:
    pgsql_data:
        driver: local
